### PR TITLE
updated quickjs to 2020-11-08

### PR DESCRIPTION
**Pull request by andrieshiemstra**
see #89

### CODE REVIEW

**Comment by andrieshiemstra** [comment]
too soon :)

**Comment by sburris0** [comment]
Can I get an update on this? Is there anything I can do to help?

**Comment by andrieshiemstra** [comment]
Well, the problem is the patch file which does not work anymore,  so we could either fix that (which is not my area of expertise atm) or we could see what quickjs-rs actually uses it for and find another way of doing that and delete the patch file..

i'll try to get into this this weekend, i think theduke is busy on other projects :)

**Comment by andrieshiemstra** [comment]
sorry i did not get back to this but https://github.com/theduke/quickjs-rs/issues/92 needed some attention first :)

this is still on top of mind

**Comment by andrieshiemstra** [comment]
i tried looking into this but it's simply out of my leage.. i'm sorry but i don't know how to fix this

**Comment by theduke** [comment]
> i tried looking into this but it's simply out of my leage.. i'm sorry but i don't know how to fix this

No shame there, patching C code when you're not familiar with C is far from trivial, especially in a codebase like QuickJS.

Also sorry for the delay. I'm looking into it right now.

**Comment by theduke** [comment]
Everything seems to actually be working now, except for a failing test with `Date` deserialization.

**Comment by theduke** [comment]
Incorporated and extended in #97  (I can't push to your branch)

**Comment by theduke** [comment]
Now merged, will be released soon.

**Comment by andrieshiemstra** [comment]
Awesome! Thanks, looking forward tot the release!

**Comment by theduke** [comment]
Already released as `0.4`.

**Pull request closed without merging**
